### PR TITLE
Move kube controller manager arguments to command line

### PR DESCRIPTION
**Pull request by csrwng**
Fixes crash on control plane pods that require service account credentials

### CODE REVIEW

**Comment by sjenning** [comment]
Tested and this fixes it. Thanks @csrwng !

**Comment by sjenning** [comment]
For the record

Hosted control plane working
```
$ oc get pod
NAME                                            READY   STATUS      RESTARTS   AGE
capa-controller-manager-7d9b4f65bb-t78zx        1/1     Running     0          8m45s
cluster-policy-controller-7d7ff4786f-6dqzq      1/1     Running     0          8m47s
cluster-version-operator-549878575b-45gph       1/1     Running     0          8m46s
control-plane-operator-558486fd69-5h2hj         1/1     Running     2          8m45s
etcd-7rbtlwx4s6                                 1/1     Running     0          8m22s
etcd-operator-667f496cdb-v75jc                  1/1     Running     0          8m46s
kube-apiserver-69bcd44b8-88knx                  3/3     Running     1          8m45s
kube-controller-manager-669786dc6c-76rnw        1/1     Running     0          2m40s
kube-scheduler-85ff88685b-q945f                 1/1     Running     0          8m47s
machine-config-server-b74b6cc69-9nbdm           1/1     Running     0          8m46s
manifests-bootstrapper                          0/1     Completed   2          8m29s
oauth-openshift-7b55c94cb7-mcxb8                1/1     Running     0          6m48s
openshift-apiserver-687975c46d-drckj            1/1     Running     0          6m47s
openshift-controller-manager-774b6c8bd6-9bwh4   1/1     Running     0          8m47s
openshift-oauth-apiserver-5b887b494d-bmxk6      1/1     Running     2          8m46s
openvpn-server-b6889884c-jmmg2                  1/1     Running     0          8m45s
router-proxy-7fdf46648b-ffzjr                   2/2     Running     0          8m45s
```

Guest cluster working
```
$ ogcv
NAME      VERSION   AVAILABLE   PROGRESSING   SINCE   STATUS
version             False       True          13m     Unable to apply 4.7.0-fc.3: some resources could not be updated
[sjennings@cerebellum hypershift]$ ogco
NAME                                       VERSION      AVAILABLE   PROGRESSING   DEGRADED   SINCE
console                                    4.7.0-fc.3   True        False         False      7m11s
dns                                        4.7.0-fc.3   True        False         False      8m8s
image-registry                             4.7.0-fc.3   True        False         False      8m32s
ingress                                    4.7.0-fc.3   True        False         False      8m6s
kube-apiserver                             4.7.0-fc.3   True        False         False      13m
kube-controller-manager                    4.7.0-fc.3   True        False         False      13m
kube-scheduler                             4.7.0-fc.3   True        False         False      13m
kube-storage-version-migrator              4.7.0-fc.3   True        False         False      8m55s
marketplace                                4.7.0-fc.3   True        False         False      8m4s
monitoring                                 4.7.0-fc.3   True        False         False      6m24s
network                                    4.7.0-fc.3   True        False         False      8m56s
node-tuning                                4.7.0-fc.3   True        False         False      8m33s
openshift-apiserver                        4.7.0-fc.3   True        False         False      13m
openshift-controller-manager               4.7.0-fc.3   True        False         False      13m
openshift-samples                          4.7.0-fc.3   True        False         False      7m48s
operator-lifecycle-manager                 4.7.0-fc.3   True        False         False      8m32s
operator-lifecycle-manager-catalog         4.7.0-fc.3   True        False         False      8m35s
operator-lifecycle-manager-packageserver   4.7.0-fc.3   True        False         False      7m29s
service-ca                                 4.7.0-fc.3   True        False         False      9m25s
storage                                    4.7.0-fc.3   True        False         False      9m29s
```
CVO `some resources could not be updated` is cause by https://github.com/openshift/cluster-authentication-operator/pull/399 not being in `fc.3`

**Comment by ironcladlou** [comment]
Does this supersede https://github.com/openshift-hive/hypershift/pull/37?

**Comment by csrwng** [comment]
Yes it does

**Pull request merged**
